### ISSUE TITLE
Suggestion - add sum to result rolls

### ISSUE THREAD

**Issue by Synisill** [ibarzabal/Genesys_old#29]
I was wondering why you chose to return a 0 value as result for the success and threat rolls.
I have read Trenloes introduction of dice action and result handlers and it seems to be a bit complicated to gather all the data, but on the other hand it seems that you filter the results before presenting them.
I think a GM would be thankful to get the total sum of successes and threat at one glance as an integer.

![sumiszero](https://user-images.githubusercontent.com/48999796/96018787-f58e1e80-0e4b-11eb-9134-bf4721230dcf.png)

**Comment by ibarzabal** [comment]
Ah I did not choose that at all. That is hardcoded into FGU, also the same with the description above the symbols. If you test it in FGC, it works ok
I am trying to see if I can change that in some way, but unfortunatelly for now that is hardcoded in the dice mechanics in FGU...

**Comment by ibarzabal** [comment]
Fixed this, updating dice roll code.
